name: Pull Request Check

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -e .
        pip install pytest pytest-cov faiss-cpu

    - name: Run tests with coverage
      run: |
        pytest --cov=chatcli --cov-report=term
